[package]
name = "attest_apple"
edition = "2024"
license = "Apache-2.0"
authors = ["Unconfirmed Labs, Inc. (os@unconfirmed.com)"]

[dependencies]
attestation = { local = "../attestation" }

[addresses]
attest_apple = "0x0"
